<?php

use Drupal\Component\EventDispatcher\Event;

/**
 * Implements hook_node_grants().
 *
 * We need to implement this hook for grant system to be enabled.
 */
function content_fixtures_test_node_grants(\Drupal\Core\Session\AccountInterface $account, $op) {}

/**
 * Implements hook_query_TAG_alter().
 */
function content_fixtures_test_query_node_access_alter($query)
{
  throw new LogicException("hook_query_ENTITY_ID_access_alter() is not supposed to be invoked.");
}
