services:
  playwright:
    # https://playwright.dev/docs/docker
    # This Playwright version should match the one in `package.json`.
    image: mcr.microsoft.com/playwright:v1.48.1
    profiles:
      - test
    networks:
      - app
      - frontend
    depends_on:
      - nginx
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /app
