version: '3'

# https://taskfile.dev/usage/#env-files
dotenv: ['.env.local', '.env']

vars:
  # https://taskfile.dev/reference/templating/
  BASE_URL: '{{.TASK_BASE_URL | default .COMPOSE_SERVER_DOMAIN | default .COMPOSE_DOMAIN | default "https://hoeringsportal.local.itkdev.dk"}}'
  DOCKER_COMPOSE: '{{.TASK_DOCKER_COMPOSE | default "docker compose"}}'
  COMPOSER_INSTALL_ARGUMENTS: '{{.TASK_COMPOSER_INSTALL_ARGUMENTS | default ""}}'

tasks:
  site-install:
    prompt: "This will reset your setup. Continue?"
    cmds:
      - task compose -- down
      - task compose-up
      - task composer-install
      - task drush -- --yes site:install --existing-config
      - task site-open
      - task site-open-admin

  site-update:
    cmds:
      - task compose-up
      - task composer-install
      - task drush -- deploy

  site-url:
    cmds:
      - task drush -- browse --no-browser
    silent: true

  site-open:
    cmds:
      - if command -v open 2>&1 >/dev/null; then open "$(task site-url)"; else echo "$(task site-url)"; fi
    silent: true

  compose:
    cmds:
      - '{{.DOCKER_COMPOSE}} {{.CLI_ARGS}}'
    silent: true

  compose-up:
    cmds:
      - task compose -- up --detach --build
    silent: true

  composer:
    cmds:
      - task compose -- exec phpfpm composer {{.CLI_ARGS}}

  composer-install:
    cmds:
      - task composer -- install {{.COMPOSER_INSTALL_ARGUMENTS}} {{.CLI_ARGS}}
    silent: true

  drush:
    cmds:
      - task compose -- exec phpfpm vendor/bin/drush --uri={{.BASE_URL}} {{.CLI_ARGS}}
    # silent: true
