<?php

/**
 * Implements hook_install().
 */
function ai_screening_project_install(): void {
  $entityType = \Drupal::entityTypeManager()->getDefinition('node');
  \Drupal::entityDefinitionUpdateManager()->updateEntityType($entityType);
}

/**
 * Implements hook_uninstall().
 */
function ai_screening_project_uninstall(): void {
  $entityType = \Drupal::entityTypeManager()->getDefinition('node');
  \Drupal::entityDefinitionUpdateManager()->updateEntityType($entityType);
}
