<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function ai_screening_project_entity_base_field_info(EntityTypeInterface $entityType): array {
  $fields = [];

  if ($entityType->id() === 'node') {
    $fields['corrupted'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Corrupted'))
      ->setDescription(t('If the project or related entities are corrupted.'))
      ->setTargetEntityTypeId($entityType->id())
      ->setReadOnly(TRUE);
  }

  return $fields;
}
