when:
  - branch: release/*
    event: push

skip_clone: true

labels:
  zone: DMZ

steps:
  - name: Run stg site update
    image: itkdev/ansible-plugin:1
    pull: true
    settings:
      id:
        from_secret: id
      secret:
        from_secret: secret
      host:
        from_secret: stg_host
      path:
        from_secret: stg_path
      user:
        from_secret: user
      actions:
        - chmod +w web/sites/default
        - chmod +w web/sites/default/settings.php
        - git reset --hard
        - git fetch origin ${CI_COMMIT_BRANCH}
        - git checkout ${CI_COMMIT_BRANCH}
        - git pull
        - itkdev-docker-compose-server up -d --force-recreate --remove-orphans
        # Build theme
        - itkdev-docker-compose-server run --rm node yarn --cwd /app/web/themes/custom/itkdev/itkdev_project_theme install
        - itkdev-docker-compose-server run --rm node yarn --cwd /app/web/themes/custom/itkdev/itkdev_base_theme install
        - itkdev-docker-compose-server run --rm node yarn --cwd /app/web/themes/custom/itkdev/itkdev_base_theme build
        # Ensure everything is owned by deploy
        - sudo chown -R deploy:deploy web
        # Cleanup theme building
        - rm -rf web/themes/custom/itkdev/*/node_modules
        # Deploy site.
        - itkdev-docker-compose-server exec phpfpm composer install --no-dev --optimize-autoloader
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes deploy

        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:check
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:update

        # Cf. task translation:import
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import                --type=not-customized --override=not-customized da ../translations/contrib-translations.da.po
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes config_translation_po:import --type=not-customized --override=not-customized da ../config/translations/config.da.po
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import-all            --type=not-customized --override=not-customized ../web/modules/custom/ai_screening/translations/
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import-all            --type=not-customized --override=not-customized ../web/modules/custom/ai_screening_project/translations/
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import-all            --type=not-customized --override=not-customized ../web/modules/custom/ai_screening_project_track/translations/
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import-all            --type=not-customized --override=not-customized ../web/modules/custom/ai_screening_reports/translations/
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import-all            --type=not-customized --override=not-customized ../web/themes/custom/itkdev/itkdev_base_theme/translations/
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes locale:import-all            --type=not-customized --override=not-customized ../web/themes/custom/itkdev/itkdev_project_theme/translations/

        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes cache:rebuild
        - itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes browse --no-browser
      cron:
        cron:
          minute: "*/5"
          hour: "*"
          day: "*"
          month: "*"
          weekday: "*"
          job: "itkdev-docker-compose-server exec phpfpm vendor/bin/drush core:cron"
