name: Playwright Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Drupal
      - name: setup-docker-and-composer
        run: |
          docker network create frontend
          docker compose pull
          docker compose up --detach
          # Important: Use --no-interaction to make https://getcomposer.org/doc/06-config.md#discard-changes have effect.
          docker compose exec --user root phpfpm composer install --no-interaction

      - name: Install site
        run: |
          # Add some local settings.
          cat > web/sites/default/settings.local.php <<'EOF'
          <?php
          $settings['hash_salt'] = '${{ github.head_ref }}';

          $settings['trusted_host_patterns'][] = '^nginx$';

          $config['system.logging']['error_level'] = ERROR_REPORTING_DISPLAY_VERBOSE;
          EOF

          # Install the site from config
          docker compose exec --user root phpfpm vendor/bin/drush site:install --existing-config --yes

      - name: Build theme
        run: |
          docker compose run --rm node yarn --cwd /app/web/themes/custom/itkdev/itkdev_base_theme install
          docker compose run --rm node yarn --cwd /app/web/themes/custom/itkdev/itkdev_base_theme build

      # Playwright
      - name: Clean up site
        run: |
          docker compose exec phpfpm vendor/bin/drush sql:query "DELETE FROM locales_target";
          docker compose exec phpfpm vendor/bin/drush cache:rebuild

      - name: Install Playwright
        run: |
          docker compose run --rm node npm install
          docker compose run --rm playwright npx playwright install

      - name: Run Playwright
        run: |
          docker compose run --rm --env CI=1 --env PLAYWRIGHT_HTML_OPEN=never playwright npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 30
