name: Translation

on:
  pull_request:
  push:

env:
  COMPOSE_USER: runner

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install site
        run: |
          docker network create frontend
          task site-install --yes

      - name: Extract translations
        run: |
          task translation:translations:extract

      - run: |
          task translation:translations:diff

  check-config-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install site
        run: |
          docker network create frontend
          task site-install --yes

      - name: Export config translations
        run: |
          task translation:config-translations:export

      - run: |
          task translation:translations:diff
