name: Translation

on:
  pull_request:
  push:

env:
  COMPOSE_USER: runner

jobs:
  check-site-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install site
        run: |
          docker network create frontend
          task site-install --yes

      - name: Site translations
        run: |
          task translation:site-translations:export

      - run: |
          task translation:translations:diff

      - name: Module translations
        run: |
          task translation:module-translations:export

      - run: |
          task translation:translations:diff

      - name: Theme translations
        run: |
          task translation:theme-translations:export

      - run: |
          task translation:translations:diff

      - name: Config translations
        run: |
          task translation:config-translations:export

      - run: |
          task translation:translations:diff
