name: Translation

on:
  pull_request:
  push:

env:
  COMPOSE_USER: runner

jobs:
  check-translations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - translation:site-translations:export
          - translation:module-translations:export
          - translation:theme-translations:export
          - translation:config-translations:export
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install site
        run: |
          docker network create frontend
          task site-install --yes

      - name: Export translations (${{ matrix.task }})
        run: |
          task ${{ matrix.task }}

      - run: |
          task translation:translations:diff
